# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 355)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./imgs/Logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"    font-family: Roboto, Arial;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.centralwidget)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("QFrame {\n"
"    color: rgb(85, 85, 85);\n"
"    background: #555;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size: 16px;\n"
"    background: Transparent;\n"
"    color: #DFDFDF;\n"
"    border: none;\n"
"    border-bottom: 1px solid #9d9d9d;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #DFDFDF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 17px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #5C5C5C;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 3px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ledSearch = QtWidgets.QLineEdit(self.frame_superior)
        self.ledSearch.setMinimumSize(QtCore.QSize(300, 30))
        self.ledSearch.setClearButtonEnabled(True)
        self.ledSearch.setObjectName("ledSearch")
        self.horizontalLayout.addWidget(self.ledSearch)
        self.btnSearch = QtWidgets.QPushButton(self.frame_superior)
        self.btnSearch.setMinimumSize(QtCore.QSize(35, 35))
        self.btnSearch.setMaximumSize(QtCore.QSize(35, 35))
        self.btnSearch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSearch.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSearch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./imgs/busqueda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSearch.setIcon(icon1)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout.addWidget(self.btnSearch)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(117, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(self.centralwidget)
        self.frame_inferior.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid #000;\n"
"    font-size: 16px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-size: 17px;\n"
"    background: #127FFF;\n"
"    color: #fff;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #2288FF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background: #0276FE;\n"
"}\n"
"\n"
"QListWidget {\n"
"    border-radius: 10px;\n"
"    border: 1px solid #000;\n"
"    padding: 5px;\n"
"    background: #F5F5F5;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    border-bottom: 1px solid;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: #B0D5FF;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background: #B0D5FF;\n"
"    color: #000;\n"
"}")
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_inferior)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.frame_izquierdo = QtWidgets.QFrame(self.frame_inferior)
        self.frame_izquierdo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_izquierdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_izquierdo.setObjectName("frame_izquierdo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_izquierdo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_izquierdo)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setStyleSheet("Font-size: 20px;\n"
"font-weight: bold;\n"
"color: #FF5C00;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_izquierdo)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ledName = QtWidgets.QLineEdit(self.frame_izquierdo)
        self.ledName.setMinimumSize(QtCore.QSize(180, 0))
        self.ledName.setAlignment(QtCore.Qt.AlignCenter)
        self.ledName.setObjectName("ledName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ledName)
        self.label_2 = QtWidgets.QLabel(self.frame_izquierdo)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ledAge = QtWidgets.QLineEdit(self.frame_izquierdo)
        self.ledAge.setAlignment(QtCore.Qt.AlignCenter)
        self.ledAge.setObjectName("ledAge")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ledAge)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btnAdd = QtWidgets.QPushButton(self.frame_izquierdo)
        self.btnAdd.setMinimumSize(QtCore.QSize(120, 40))
        self.btnAdd.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btnAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAdd.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./imgs/agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon2)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_3.addWidget(self.btnAdd)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.gridLayout.addWidget(self.frame_izquierdo, 1, 1, 1, 1)
        self.frame_central = QtWidgets.QFrame(self.frame_inferior)
        self.frame_central.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_central.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_central.setObjectName("frame_central")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_central)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_central)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setStyleSheet("Font-size: 20px;\n"
"font-weight: bold;\n"
"color: #FF5C00;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.list = QtWidgets.QListWidget(self.frame_central)
        self.list.setMinimumSize(QtCore.QSize(233, 140))
        self.list.setMaximumSize(QtCore.QSize(233, 16777215))
        self.list.setObjectName("list")
        item = QtWidgets.QListWidgetItem()
        self.list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.list.addItem(item)
        self.verticalLayout_3.addWidget(self.list)
        self.lblIndicator = QtWidgets.QLabel(self.frame_central)
        self.lblIndicator.setStyleSheet("font-size: 15px;\n"
"font-style: italic;")
        self.lblIndicator.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIndicator.setObjectName("lblIndicator")
        self.verticalLayout_3.addWidget(self.lblIndicator)
        self.gridLayout.addWidget(self.frame_central, 1, 2, 1, 1)
        self.frame_derecho = QtWidgets.QFrame(self.frame_inferior)
        self.frame_derecho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_derecho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_derecho.setObjectName("frame_derecho")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_derecho)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.btnEdit = QtWidgets.QPushButton(self.frame_derecho)
        self.btnEdit.setMinimumSize(QtCore.QSize(40, 40))
        self.btnEdit.setMaximumSize(QtCore.QSize(40, 40))
        self.btnEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnEdit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./imgs/lapiz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEdit.setIcon(icon3)
        self.btnEdit.setIconSize(QtCore.QSize(17, 17))
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout_4.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(self.frame_derecho)
        self.btnDelete.setMinimumSize(QtCore.QSize(40, 40))
        self.btnDelete.setMaximumSize(QtCore.QSize(40, 40))
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDelete.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./imgs/basura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon4)
        self.btnDelete.setIconSize(QtCore.QSize(18, 18))
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout_4.addWidget(self.btnDelete)
        self.btnClean = QtWidgets.QPushButton(self.frame_derecho)
        self.btnClean.setMinimumSize(QtCore.QSize(40, 40))
        self.btnClean.setMaximumSize(QtCore.QSize(40, 40))
        self.btnClean.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClean.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClean.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./imgs/broom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClean.setIcon(icon5)
        self.btnClean.setIconSize(QtCore.QSize(18, 18))
        self.btnClean.setObjectName("btnClean")
        self.verticalLayout_4.addWidget(self.btnClean)
        spacerItem10 = QtWidgets.QSpacerItem(20, 58, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.gridLayout.addWidget(self.frame_derecho, 1, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 4, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_inferior)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventana Principal"))
        self.ledSearch.setPlaceholderText(_translate("MainWindow", "Buscar..."))
        self.btnSearch.setToolTip(_translate("MainWindow", "Buscar (Ctrl + S)"))
        self.btnSearch.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.label_3.setText(_translate("MainWindow", "DATOS"))
        self.label.setText(_translate("MainWindow", "Nombre:"))
        self.label_2.setText(_translate("MainWindow", "Edad:"))
        self.btnAdd.setToolTip(_translate("MainWindow", "(Enter)"))
        self.btnAdd.setText(_translate("MainWindow", " Agregar"))
        self.btnAdd.setShortcut(_translate("MainWindow", "Return"))
        self.label_4.setText(_translate("MainWindow", "LISTA"))
        __sortingEnabled = self.list.isSortingEnabled()
        self.list.setSortingEnabled(False)
        item = self.list.item(0)
        item.setText(_translate("MainWindow", "Nuevo elemento"))
        item = self.list.item(1)
        item.setText(_translate("MainWindow", "Nuevo elemento"))
        self.list.setSortingEnabled(__sortingEnabled)
        self.lblIndicator.setText(_translate("MainWindow", "En lista: n"))
        self.btnEdit.setToolTip(_translate("MainWindow", "Editar (E)"))
        self.btnEdit.setShortcut(_translate("MainWindow", "E"))
        self.btnDelete.setToolTip(_translate("MainWindow", "Eliminar (D)"))
        self.btnDelete.setShortcut(_translate("MainWindow", "D"))
        self.btnClean.setToolTip(_translate("MainWindow", "Vaciar lista (C)"))
        self.btnClean.setShortcut(_translate("MainWindow", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
